AddonManager_Settings = {
	["ShowMiniBarBorder"] = false,
	["MiniY"] = 74.399993896484,
	["FrameStrata"] = 2,
	["MovePassiveToBack"] = true,
	["ShowOnlyNamesInMiniBar"] = true,
	["ShowMiniBar"] = false,
	["MiniX"] = 115.23406982422,
	["LockMiniBar"] = true,
	["ShowMinimapButton"] = false,
	["AutoHideMiniBar"] = false,
	["ShowSlashCmdInsteadOfCat"] = false,
}
AddonManager_UncheckedAddons = {
}
CHATFRAME_ANCHORS = {
	[1] = {
		["relativeTo"] = "UIParent",
		["point"] = "BOTTOMLEFT",
		["relativePoint"] = "BOTTOMLEFT",
		["offsetY"] = -36,
		["offsetX"] = 0,
		["size"] = {
			["y"] = 200,
			["x"] = 460,
		},
	},
	[2] = {
		["relativeTo"] = "ChatFrame1",
		["point"] = "TOPLEFT",
		["relativePoint"] = "TOPLEFT",
		["offsetY"] = 0,
		["offsetX"] = 0,
		["size"] = {
			["y"] = 200,
			["x"] = 460,
		},
	},
	[3] = {
		["relativeTo"] = "ChatFrame1",
		["point"] = "TOPLEFT",
		["relativePoint"] = "TOPLEFT",
		["offsetY"] = 0,
		["offsetX"] = 0,
		["size"] = {
			["y"] = 200,
			["x"] = 460,
		},
	},
	[4] = {
		["relativeTo"] = "ChatFrame1",
		["point"] = "TOPLEFT",
		["relativePoint"] = "TOPLEFT",
		["offsetY"] = 0,
		["offsetX"] = 0,
		["size"] = {
			["y"] = 200,
			["x"] = 460,
		},
	},
	[5] = {
		["relativeTo"] = "UIParent",
		["point"] = "TOPLEFT",
		["relativePoint"] = "TOPLEFT",
		["offsetY"] = 0,
		["offsetX"] = 0,
		["size"] = {
			["y"] = 182,
			["x"] = 370,
		},
	},
	[6] = {
		["relativeTo"] = "UIParent",
		["point"] = "TOPLEFT",
		["relativePoint"] = "TOPLEFT",
		["offsetY"] = 0,
		["offsetX"] = 0,
		["size"] = {
			["y"] = 182,
			["x"] = 370,
		},
	},
	[7] = {
		["relativeTo"] = "UIParent",
		["point"] = "TOPLEFT",
		["relativePoint"] = "TOPLEFT",
		["offsetY"] = 0,
		["offsetX"] = 0,
		["size"] = {
			["y"] = 182,
			["x"] = 370,
		},
	},
	[8] = {
		["relativeTo"] = "UIParent",
		["point"] = "TOPLEFT",
		["relativePoint"] = "TOPLEFT",
		["offsetY"] = 0,
		["offsetX"] = 0,
		["size"] = {
			["y"] = 182,
			["x"] = 370,
		},
	},
	[9] = {
		["relativeTo"] = "UIParent",
		["point"] = "TOPLEFT",
		["relativePoint"] = "TOPLEFT",
		["offsetY"] = 0,
		["offsetX"] = 0,
		["size"] = {
			["y"] = 182,
			["x"] = 370,
		},
	},
	[10] = {
		["relativeTo"] = "UIParent",
		["point"] = "TOPLEFT",
		["relativePoint"] = "TOPLEFT",
		["offsetY"] = 0,
		["offsetX"] = 0,
		["size"] = {
			["y"] = 182,
			["x"] = 370,
		},
	},
}
ChannelChange_Color = {
	[1] = {
		["a"] = 1,
		["b"] = 1,
		["g"] = 1,
		["r"] = 1,
	},
	[2] = {
		["a"] = 1,
		["b"] = 0.60784316062927,
		["g"] = 0.87450981140137,
		["r"] = 0.76862746477127,
	},
	[3] = {
		["a"] = 1,
		["b"] = 0.25098040699959,
		["g"] = 1,
		["r"] = 0.25098040699959,
	},
	[4] = {
		["a"] = 1,
		["b"] = 0.94901961088181,
		["g"] = 0.74901962280273,
		["r"] = 0,
	},
	[5] = {
		["a"] = 1,
		["b"] = 0.4705882370472,
		["g"] = 0.60000002384186,
		["r"] = 0.96078431606293,
	},
	[6] = {
		["a"] = 1,
		["b"] = 0.86274510622025,
		["g"] = 0.4705882370472,
		["r"] = 0.91764706373215,
	},
	[7] = {
		["a"] = 1,
		["b"] = 0.86274510622025,
		["g"] = 0.4705882370472,
		["r"] = 0.91764706373215,
	},
	[8] = {
		["a"] = 1,
		["b"] = 1,
		["g"] = 1,
		["r"] = 0,
	},
	[9] = {
		["a"] = 1,
		["b"] = 1,
		["g"] = 1,
		["r"] = 0,
	},
	[10] = {
		["a"] = 1,
		["b"] = 1,
		["g"] = 1,
		["r"] = 0,
	},
	[11] = {
		["a"] = 1,
		["b"] = 1,
		["g"] = 1,
		["r"] = 0,
	},
	[12] = {
		["a"] = 1,
		["b"] = 1,
		["g"] = 1,
		["r"] = 0,
	},
	[13] = {
		["a"] = 1,
		["b"] = 1,
		["g"] = 1,
		["r"] = 0,
	},
	[14] = {
		["a"] = 1,
		["b"] = 1,
		["g"] = 1,
		["r"] = 0,
	},
	[15] = {
		["a"] = 1,
		["b"] = 1,
		["g"] = 1,
		["r"] = 0,
	},
	[16] = {
		["a"] = 1,
		["b"] = 1,
		["g"] = 1,
		["r"] = 0,
	},
}
ChannelChange_Color_Old = {
	[1] = {
		["a"] = 1,
		["b"] = 1,
		["g"] = 1,
		["r"] = 1,
	},
	[2] = {
		["a"] = 1,
		["b"] = 0.60784316062927,
		["g"] = 0.87450981140137,
		["r"] = 0.76862746477127,
	},
	[3] = {
		["a"] = 1,
		["b"] = 0.25098040699959,
		["g"] = 1,
		["r"] = 0.25098040699959,
	},
	[4] = {
		["a"] = 1,
		["b"] = 0.94901961088181,
		["g"] = 0.74901962280273,
		["r"] = 0,
	},
	[5] = {
		["a"] = 1,
		["b"] = 0.4705882370472,
		["g"] = 0.60000002384186,
		["r"] = 0.96078431606293,
	},
	[6] = {
		["a"] = 1,
		["b"] = 0.86274510622025,
		["g"] = 0.4705882370472,
		["r"] = 0.91764706373215,
	},
	[7] = {
		["a"] = 1,
		["b"] = 0.86274510622025,
		["g"] = 0.4705882370472,
		["r"] = 0.91764706373215,
	},
	[8] = {
		["a"] = 1,
		["b"] = 1,
		["g"] = 1,
		["r"] = 0,
	},
	[9] = {
		["a"] = 1,
		["b"] = 1,
		["g"] = 1,
		["r"] = 0,
	},
	[10] = {
		["a"] = 1,
		["b"] = 1,
		["g"] = 1,
		["r"] = 0,
	},
	[11] = {
		["a"] = 1,
		["b"] = 1,
		["g"] = 1,
		["r"] = 0,
	},
	[12] = {
		["a"] = 1,
		["b"] = 1,
		["g"] = 1,
		["r"] = 0,
	},
	[13] = {
		["a"] = 1,
		["b"] = 1,
		["g"] = 1,
		["r"] = 0,
	},
	[14] = {
		["a"] = 1,
		["b"] = 1,
		["g"] = 1,
		["r"] = 0,
	},
	[15] = {
		["a"] = 1,
		["b"] = 1,
		["g"] = 1,
		["r"] = 0,
	},
	[16] = {
		["a"] = 1,
		["b"] = 1,
		["g"] = 1,
		["r"] = 0,
	},
}
DN_Options = {
	["verbose_quest"] = true,
	["showcharlevel"] = true,
	["ZBag_Hook"] = true,
	["verbose"] = false,
	["filter"] = {
		["daily"] = true,
		["public"] = true,
		["epic"] = true,
		["xp"] = true,
		["energy"] = true,
		["repeatable"] = true,
	},
	["takefilter"] = false,
	["TT_mobs"] = true,
	["version"] = "v7.2",
	["TT_items"] = true,
	["dqionly"] = true,
	["TT_dialog"] = true,
	["mark_undone_quests"] = false,
	["itemcount"] = true,
}
Fusion_Settings = {
	["Enabled"] = true,
	["Blue"] = false,
	["Purple"] = false,
	["White"] = true,
	["UsePurifiedFusionStones"] = false,
	["UseClearBag"] = false,
	["Green"] = false,
	["UseRandomFusionStones"] = true,
	["UseFusionStones"] = false,
	["Speed"] = 1.5,
	["UseItemlist"] = true,
}
GOODSPACK_AUTOOPEN = false
GuildFrameInfo = {
	["ShowOffline"] = false,
}
Lootomatic_Settings = {
	["DropQuest"] = true,
	["BackUp"] = false,
	["RollResults"] = {
		[1] = {
			[1] = true,
			[2] = true,
			[3] = true,
		},
		[2] = {
			[1] = true,
			[2] = true,
			[3] = true,
		},
		[3] = {
			[1] = true,
			[2] = true,
			[3] = true,
		},
		[4] = {
			[1] = true,
			[2] = true,
			[3] = true,
		},
		[5] = {
			[1] = true,
			[2] = true,
			[3] = true,
		},
		[6] = {
			[1] = true,
			[2] = true,
			[3] = true,
		},
	},
	["AM"] = true,
	["ItemFilter"] = {
	},
	["RollQuest"] = true,
	["RollTooltip"] = true,
	["AutoLoot"] = 7,
	["ChatOutput"] = false,
	["LootClose"] = false,
	["RollFrameD"] = -64,
	["ItemFilterY"] = 300,
	["DropAmmo"] = 20,
	["LootMaster"] = false,
	["AutoPass"] = 1,
	["RollDelay"] = 2,
	["Roll"] = 3,
	["ChatColor"] = {
		["b"] = 0.5,
		["g"] = 1,
		["r"] = 1,
	},
	["LootMove"] = false,
	["Enabled"] = true,
	["DropBugFix"] = false,
	["ItemFilterX"] = 450,
	["AutoLootBoss"] = false,
	["RollFrameX"] = 121.25,
	["DropAuto"] = false,
	["LootQuest"] = false,
	["ListFilter"] = false,
	["RollNewStyle"] = true,
	["Version"] = "v1.40",
	["AutoGreed"] = 1,
	["ChatFrames"] = {
		[1] = true,
		[2] = true,
		[3] = true,
		[4] = true,
		[5] = true,
		[6] = true,
		[7] = true,
		[8] = true,
		[9] = true,
		[10] = true,
	},
	["DropTime"] = 10,
	["DropItems"] = 5,
	["RollFrameY"] = -232.5,
}
MSN_INFO = {
	["CHANNEL9"] = {
		["y"] = 0.263,
		["x"] = 0.35,
		["w"] = 326,
		["h"] = 300,
	},
	["CHANNEL7"] = {
		["y"] = 0.261,
		["x"] = 0.33,
		["w"] = 326,
		["h"] = 300,
	},
	["GUILD"] = {
		["auto"] = false,
		["r"] = 255,
		["g"] = 255,
		["y"] = 0.261,
		["x"] = 0.31,
		["h"] = 300,
		["w"] = 326,
		["b"] = 255,
		["font"] = 12,
	},
	["CHANNEL1"] = {
		["y"] = 0.265,
		["x"] = 0.31,
		["w"] = 326,
		["h"] = 300,
	},
	["CHANNEL3"] = {
		["y"] = 0.267,
		["x"] = 0.31,
		["w"] = 326,
		["h"] = 300,
	},
	["CHANNEL"] = {
		["font"] = 12,
		["auto"] = false,
		["r"] = 255,
		["h"] = 300,
		["w"] = 326,
		["g"] = 255,
		["b"] = 255,
	},
	["PARTY"] = {
		["auto"] = false,
		["r"] = 255,
		["g"] = 255,
		["y"] = 0.26,
		["x"] = 0.31,
		["h"] = 300,
		["w"] = 326,
		["b"] = 255,
		["font"] = 12,
	},
	["CHANNEL8"] = {
		["y"] = 0.262,
		["x"] = 0.34,
		["w"] = 326,
		["h"] = 300,
	},
	["YELL"] = {
		["auto"] = false,
		["r"] = 255,
		["g"] = 255,
		["y"] = 0.263,
		["x"] = 0.31,
		["h"] = 300,
		["w"] = 326,
		["b"] = 255,
		["font"] = 12,
	},
	["CHANNEL6"] = {
		["y"] = 0.26,
		["x"] = 0.32,
		["w"] = 326,
		["h"] = 300,
	},
	["CHANNEL5"] = {
		["y"] = 0.269,
		["x"] = 0.31,
		["w"] = 326,
		["h"] = 300,
	},
	["ZONE"] = {
		["auto"] = false,
		["r"] = 255,
		["g"] = 255,
		["y"] = 0.264,
		["x"] = 0.31,
		["h"] = 300,
		["w"] = 326,
		["b"] = 255,
		["font"] = 12,
	},
	["CHANNEL4"] = {
		["y"] = 0.268,
		["x"] = 0.31,
		["w"] = 326,
		["h"] = 300,
	},
	["CHANNEL2"] = {
		["y"] = 0.266,
		["x"] = 0.31,
		["w"] = 326,
		["h"] = 300,
	},
	["WHISPER"] = {
		["auto"] = true,
		["r"] = 255,
		["g"] = 255,
		["y"] = 0.262,
		["x"] = 0.31,
		["h"] = 300,
		["w"] = 326,
		["b"] = 255,
		["font"] = 12,
	},
}
QH_DynData = {
	["7.4.0.2914"] = {
		[421865] = {
			[0] = {
				["s"] = {
					[1] = 112497,
				},
			},
			[204180] = {
				[100] = {
					[1] = {
						["y"] = 0.397,
						["x"] = 0.578,
					},
				},
			},
		},
		[420660] = {
			[0] = {
				["s"] = {
					[1] = 110484,
				},
			},
		},
	},
}
QH_Options = {
	["tracker_zone_only"] = true,
	["map_all_points"] = false,
	["LineCount"] = 20,
	["text_size"] = 14,
	["tracker_body"] = true,
	["minimap"] = false,
	["tracker_title"] = true,
	["version"] = 70201,
	["navi"] = true,
	["tracker"] = true,
	["layericons"] = true,
	["map_full_info"] = false,
}
QuestStateSettings = {
	["changeSpeakFrame"] = true,
	["publicQuests"] = false,
	["normalQuests"] = true,
	["dailyQuests"] = false,
	["sameMap"] = false,
}
SCROLLBANNERFRAME_HIDE = false
SUI_questtrack_config = {
	["QT_title"] = 14,
	["QT_item"] = 14,
}
UMMConfig = {
	["Characters"] = {
		[1] = "Qemu",
	},
	["NewMail"] = {
	},
	["Settings"] = {
		["DeleteDelay"] = 1,
		["AudioWarning"] = true,
	},
}
WoWMapPOI_Nodes = {
}
WoWMapSettings = {
	["UseShiftModifier"] = false,
	["Version"] = "v7.2",
	["DrawAllQuestPOIs"] = false,
	["POIs"] = {
	},
}
g_AreaMapConfig = {
	["size"] = 30,
	["showTrackNpc"] = 1,
	["alpha"] = 100,
	["showParty"] = 1,
}
g_ChannelChangeConfig = {
	["Enter"] = false,
	["Setting"] = false,
	["Lock"] = true,
	["Order"] = 3,
	["HighLight_Persist"] = false,
	["HighLight"] = true,
	["Show"] = true,
}
g_FocusFrameOption = {
	["HpHeight"] = 10,
	["SpacingY"] = 1,
	["HideNobady"] = 1,
	["SpacingX"] = 1,
	["Width"] = 50,
	["NameFontSize"] = 10,
	["ShowTargetTarget"] = 1,
	["ShowTarget"] = 1,
	["ClassColor"] = 2,
	["MaxFocus"] = 6,
	["MpHeight"] = 2,
}
g_IM2_History = {
	["SteamLogin"] = {
	},
}
g_MinimapDate = {
	[1] = true,
	[2] = true,
	[3] = true,
	[5] = true,
	[6] = true,
	[7] = true,
	[8] = true,
	[9] = true,
	[10] = true,
	[11] = true,
	["ZoomIndex"] = 3,
	[21] = true,
}
g_QuestTrackInfo = {
}
g_RaidFrameOption = {
	["HpHeight"] = 15,
	["HideNobady"] = 1,
	["HideNobadyParty"] = 1,
	["PartySpacingY"] = 4,
	["AutoAnchor"] = 1,
	["HideBackdrop"] = 1,
	["Vertical"] = 1,
	["DeBufCount"] = 3,
	["Spacing"] = 2,
	["BufShow"] = false,
	["PartyRow"] = 2,
	["DeBufPosType"] = 1,
	["MpHeight"] = 3,
	["ClassColor"] = 2,
	["Lock"] = 1,
	["BufSize"] = 7,
	["BufRowCount"] = 1,
	["BufCount"] = 3,
	["BufPosType"] = 1,
	["DeBufSize"] = 7,
	["Width"] = 61,
	["NameFontSize"] = 10,
	["HidePartyInRaid"] = 1,
	["DeBufShow"] = 1,
	["PartySpacingX"] = 9,
	["DeBufSpacing"] = 0,
	["BufSpacing"] = 0,
	["RaidFocus"] = 1,
	["DeBufRowCount"] = 1,
}
g_RaidFrameShowOption = {
	["Group 2"] = 1,
	["Group 6"] = 1,
	["Group 5"] = 1,
	["Group 3"] = 1,
	["Group 4"] = 1,
	["Group 1"] = 1,
}
g_UIPanelAnchorFrameOptions = {
	["RaidPartyOptionFrame6"] = {
		["y"] = 212,
		["x"] = 152,
		["point"] = "TOPLEFT",
		["relativePoint"] = "TOPLEFT",
		["relativeTo"] = "RaidPartyOptionFrame1",
	},
	["RaidPartyOptionFrame2"] = {
		["y"] = 0,
		["x"] = 152,
		["point"] = "TOPLEFT",
		["relativePoint"] = "TOPLEFT",
		["relativeTo"] = "RaidPartyOptionFrame1",
	},
	["PlayerFrameWorldBattleGroundButton"] = {
		["y"] = 66.749996442348,
		["x"] = 229.58548710368,
		["point"] = "TOPLEFT",
		["relativePoint"] = "TOPLEFT",
		["relativeTo"] = "UIParent",
	},
	["PEFs_Item6_Button"] = {
		["y"] = 0,
		["x"] = 0,
		["point"] = "TOPLEFT",
		["relativePoint"] = "TOPLEFT",
		["relativeTo"] = "PEFs_Item6",
	},
	["MinimapBeautyStudioButton"] = {
		["y"] = -11.979999542236,
		["x"] = -79.09700012207,
		["point"] = "CENTER",
		["relativePoint"] = "CENTER",
		["relativeTo"] = "MinimapViewFrame",
	},
	["Lootomatic_Minimap"] = {
		["y"] = 66.750001210719,
		["x"] = 277.58548829577,
		["point"] = "TOPLEFT",
		["relativePoint"] = "TOPLEFT",
		["relativeTo"] = "UIParent",
	},
	["PEFs_Item7_Button"] = {
		["y"] = 0,
		["x"] = 0,
		["point"] = "TOPLEFT",
		["relativePoint"] = "TOPLEFT",
		["relativeTo"] = "PEFs_Item7",
	},
	["RaidPartyFrame2"] = {
		["y"] = 152,
		["x"] = 0,
		["point"] = "TOPLEFT",
		["relativePoint"] = "TOPLEFT",
		["relativeTo"] = "RaidPartyFrame1",
	},
	["PEFs_Item5_Button"] = {
		["y"] = 0,
		["x"] = 0,
		["point"] = "TOPLEFT",
		["relativePoint"] = "TOPLEFT",
		["relativeTo"] = "PEFs_Item5",
	},
	["ChatFrameChannelChangeResizeButton"] = {
		["y"] = -275.75002617016,
		["x"] = 419.0000090152,
		["point"] = "BOTTOMLEFT",
		["relativePoint"] = "BOTTOMLEFT",
		["relativeTo"] = "UIParent",
	},
	["QH_QuestTracker_HeadMini"] = {
		["y"] = -9,
		["x"] = -8,
		["point"] = "TOPLEFT",
		["relativePoint"] = "TOPLEFT",
		["relativeTo"] = "QH_QuestTracker",
	},
	["PEFs_Item10_Button"] = {
		["y"] = 0,
		["x"] = 0,
		["point"] = "TOPLEFT",
		["relativePoint"] = "TOPLEFT",
		["relativeTo"] = "PEFs_Item10",
	},
	["MinimapFrameBattleGroundButton"] = {
		["y"] = -27.170000076294,
		["x"] = 75.23999786377,
		["point"] = "CENTER",
		["relativePoint"] = "CENTER",
		["relativeTo"] = "MinimapViewFrame",
	},
	["MainActionBarFrame"] = {
		["y"] = -191.00013396144,
		["x"] = -38.957518950738,
		["point"] = "BOTTOM",
		["relativePoint"] = "BOTTOM",
		["relativeTo"] = "UIParent",
	},
	["MinimapFrameRestoreUIButton"] = {
		["y"] = 24.409999847412,
		["x"] = 76.180000305176,
		["point"] = "CENTER",
		["relativePoint"] = "CENTER",
		["relativeTo"] = "MinimapViewFrame",
	},
	["PetBookFrameButton"] = {
		["y"] = 66.749996442348,
		["x"] = 253.58548293135,
		["point"] = "TOPLEFT",
		["relativePoint"] = "TOPLEFT",
		["relativeTo"] = "UIParent",
	},
	["RaidPartyFrame3"] = {
		["y"] = 0,
		["x"] = 70,
		["point"] = "TOPLEFT",
		["relativePoint"] = "TOPLEFT",
		["relativeTo"] = "RaidPartyFrame1",
	},
	["LeftActionBarFrame"] = {
		["y"] = -77.00018239021,
		["x"] = -38.957518950738,
		["point"] = "BOTTOM",
		["relativePoint"] = "BOTTOM",
		["relativeTo"] = "UIParent",
	},
	["PEFs_Item2_Button"] = {
		["y"] = 0,
		["x"] = 0,
		["point"] = "TOPLEFT",
		["relativePoint"] = "TOPLEFT",
		["relativeTo"] = "PEFs_Item2",
	},
	["PlayerFramePartyBoardButton"] = {
		["y"] = 66.749996442348,
		["x"] = 205.58548173926,
		["point"] = "TOPLEFT",
		["relativePoint"] = "TOPLEFT",
		["relativeTo"] = "UIParent",
	},
	["SUI_QuestTrackBar"] = {
		["y"] = 327.24999893829,
		["x"] = -47.499963529409,
		["point"] = "TOPRIGHT",
		["relativePoint"] = "TOPRIGHT",
		["relativeTo"] = "UIParent",
	},
	["PlayerFramePetButton"] = {
		["y"] = 66.750001210719,
		["x"] = 181.58547637484,
		["point"] = "TOPLEFT",
		["relativePoint"] = "TOPLEFT",
		["relativeTo"] = "UIParent",
	},
	["RaidPartyOptionFrame4"] = {
		["y"] = 106,
		["x"] = 152,
		["point"] = "TOPLEFT",
		["relativePoint"] = "TOPLEFT",
		["relativeTo"] = "RaidPartyOptionFrame1",
	},
	["RaidPartyOptionFrame5"] = {
		["y"] = 212,
		["x"] = 0,
		["point"] = "TOPLEFT",
		["relativePoint"] = "TOPLEFT",
		["relativeTo"] = "RaidPartyOptionFrame1",
	},
	["MinimapNpcTrackButton"] = {
		["y"] = -39.85599899292,
		["x"] = -69.363998413086,
		["point"] = "CENTER",
		["relativePoint"] = "CENTER",
		["relativeTo"] = "MinimapViewFrame",
	},
	["RaidPartyFrame4"] = {
		["y"] = 152,
		["x"] = 70,
		["point"] = "TOPLEFT",
		["relativePoint"] = "TOPLEFT",
		["relativeTo"] = "RaidPartyFrame1",
	},
	["QH_QuestTracker"] = {
		["y"] = 119.99999672174,
		["x"] = 161.24999629334,
		["point"] = "TOPLEFT",
		["relativePoint"] = "TOPLEFT",
		["relativeTo"] = "UIParent",
	},
	["PEFs_Item1_Button"] = {
		["y"] = 0,
		["x"] = 0,
		["point"] = "TOPLEFT",
		["relativePoint"] = "TOPLEFT",
		["relativeTo"] = "PEFs_Item1",
	},
	["MinimapFrameStoreButton"] = {
		["y"] = 19.108999252319,
		["x"] = -77.68399810791,
		["point"] = "CENTER",
		["relativePoint"] = "CENTER",
		["relativeTo"] = "MinimapViewFrame",
	},
	["PEFs_Item3_Button"] = {
		["y"] = 0,
		["x"] = 0,
		["point"] = "TOPLEFT",
		["relativePoint"] = "TOPLEFT",
		["relativeTo"] = "PEFs_Item3",
	},
	["MinimapFrameBulletinButton"] = {
		["y"] = -61.729000091553,
		["x"] = -50.880001068115,
		["point"] = "CENTER",
		["relativePoint"] = "CENTER",
		["relativeTo"] = "MinimapViewFrame",
	},
	["PEFs_Item4_Button"] = {
		["y"] = 0,
		["x"] = 0,
		["point"] = "TOPLEFT",
		["relativePoint"] = "TOPLEFT",
		["relativeTo"] = "PEFs_Item4",
	},
	["PEFs_Item9_Button"] = {
		["y"] = 0,
		["x"] = 0,
		["point"] = "TOPLEFT",
		["relativePoint"] = "TOPLEFT",
		["relativeTo"] = "PEFs_Item9",
	},
	["BottomActionBarFrame"] = {
		["y"] = -153.00008970499,
		["x"] = -38.957518950738,
		["point"] = "BOTTOM",
		["relativePoint"] = "BOTTOM",
		["relativeTo"] = "UIParent",
	},
	["MinimapFrameQuestTrackButton"] = {
		["y"] = 45.284999847412,
		["x"] = -65.947998046875,
		["point"] = "CENTER",
		["relativePoint"] = "CENTER",
		["relativeTo"] = "MinimapViewFrame",
	},
	["PEFs_Item8_Button"] = {
		["y"] = 0,
		["x"] = 0,
		["point"] = "TOPLEFT",
		["relativePoint"] = "TOPLEFT",
		["relativeTo"] = "PEFs_Item8",
	},
	["MinimapFrameTopupButton"] = {
		["y"] = 66.749996442348,
		["x"] = 157.58546624205,
		["point"] = "TOPLEFT",
		["relativePoint"] = "TOPLEFT",
		["relativeTo"] = "UIParent",
	},
	["RaidPartyOptionFrame3"] = {
		["y"] = 106,
		["x"] = 0,
		["point"] = "TOPLEFT",
		["relativePoint"] = "TOPLEFT",
		["relativeTo"] = "RaidPartyOptionFrame1",
	},
	["RightActionBarFrame"] = {
		["y"] = -115.0001360476,
		["x"] = -38.957518950738,
		["point"] = "BOTTOM",
		["relativePoint"] = "BOTTOM",
		["relativeTo"] = "UIParent",
	},
	["RaidPartyFrame5"] = {
		["y"] = 0,
		["x"] = 140,
		["point"] = "TOPLEFT",
		["relativePoint"] = "TOPLEFT",
		["relativeTo"] = "RaidPartyFrame1",
	},
	["MinimapFrameOptionButton"] = {
		["y"] = 66.078002929688,
		["x"] = -45.095001220703,
		["point"] = "CENTER",
		["relativePoint"] = "CENTER",
		["relativeTo"] = "MinimapViewFrame",
	},
	["RaidPartyFrame6"] = {
		["y"] = 152,
		["x"] = 140,
		["point"] = "TOPLEFT",
		["relativePoint"] = "TOPLEFT",
		["relativeTo"] = "RaidPartyFrame1",
	},
}
g_WorldMapConfig = {
	["showNewQuest"] = true,
	["showTrustQuest"] = true,
	["showParty"] = 1,
	["showUnfinishQuest"] = false,
	["size"] = 90,
	["hideQuestTrackFrame"] = true,
	["showFinishedQuest"] = true,
	["showTrackNpc"] = 1,
	["showQuestNpc"] = 1,
	["hideLowQuest"] = 1,
}
pbInfoCharData = {
}
pbInfoSettings = {
	["QuestTrackerFontSizes"] = {
		[1] = 14,
		[2] = 12,
		[3] = 10,
	},
	["GameTooltipPosition"] = {
		[1] = 400,
		[2] = 300,
	},
	["MODIFYBLOODBARS"] = true,
	["MATINFOITEMCOUNT"] = true,
	["CHATFRAMEFILTERTITLES"] = false,
	["MODIFYTOOLTIP"] = true,
	["THREATMETERHIDEONNOPARTY"] = false,
	["CHATFRAMEHIDEXPTP"] = false,
	["QUESTTRACKERSHOWDAILIESCOUNTER"] = true,
	["THREATMETERLOCK"] = false,
	["ALLNPC"] = false,
	["QUESTTRACKERPROGRESSCOLORFADE"] = true,
	["QUESTTRACKERHIGHLIGHTDAILIES"] = true,
	["QUESTTRACKEROPENQUESTBOOK"] = true,
	["QuestTrackerPosition"] = {
		[1] = 400,
		[2] = 300,
	},
	["SHOWCRIT"] = false,
	["PLAYERINFO"] = true,
	["MATINFOITEMCOUNTIV"] = false,
	["TOOLTIPSHOWPLAYERINFO"] = false,
	["extraLanguage"] = false,
	["STICKYALLTOOLTIPS"] = false,
	["CASTINGBARMOVEONLOAD"] = false,
	["MODIFYHEALTHBAR"] = true,
	["MATINFOITEMCOUNTBANK"] = true,
	["TIMESTAMPNOTINCOMBATLOG"] = true,
	["CHATFRAMESHOWPLAYERINFO"] = true,
	["HEALTHCOLORFADE"] = true,
	["CHATLOG"] = false,
	["QUESTTRACKERTOOLTIPDESCRIPTION"] = true,
	["THREATMETERRELATIVETOMAXTHREAT"] = false,
	["CHATFRAMEHIDEPROGRESS"] = false,
	["THREATMETERHIDEONNOTARGET"] = false,
	["CastingBarPosition"] = {
		[1] = 0,
		[2] = 0,
	},
	["GameTooltipAlpha"] = 1,
	["ThousandsSeparatorFormat"] = ".",
	["STICKYTOOLTIP"] = false,
	["QUESTTRACKERSORTASC"] = false,
	["THREATMETER"] = false,
	["SHOWRELATION"] = true,
	["QUESTTRACKERSHOWTITLE"] = true,
	["CHATFRAMEHIDEXPTPDEBT"] = false,
	["HEALTHBARSHOWPERCENTAGE"] = true,
	["SHOWMOUSEOVERTARGET"] = false,
	["SHOWMATERIALINFO"] = true,
	["TimeStampFormat"] = "%H:%M:%S",
	["BLOODBARSCOLORFADE"] = false,
	["HEALTHBARCOLORFADE"] = false,
	["QUESTTRACKERTOOLTIP"] = true,
	["THREATMETERSHOWTITLE"] = true,
	["PLAYERINFOSAVEDATA"] = false,
	["ThreatMeterAlpha"] = 1,
	["TIMESTAMP"] = true,
	["SHOWMANA"] = true,
	["TOOLTIPSHOWRACE"] = true,
	["THREATMETERSHOWREALTHREAT"] = true,
	["SHOWCLOCKTOOLTIP"] = false,
	["ThreatMeterDisplayLimit"] = 0,
	["HIDESCROLLBANNER"] = {
		[1] = false,
		[2] = 1,
	},
	["QUESTTRACKERTOOLTIPRIGHT"] = false,
	["ChatLogMaxLinesPerChat"] = 99,
	["CASTINGBARSHOWCASTTIME"] = false,
	["THREATMETEWARNTARGETTARGETTARGET"] = true,
	["ThreatMeterDelay"] = 1,
	["ThreatMeterPosition"] = {
		[1] = 400,
		[2] = 300,
	},
	["CHATFRAMEHIDEPROGRESSGATHER"] = false,
	["ENABLE"] = true,
	["QuestTrackerColors"] = {
		[1] = {
			[1] = 0.8,
			[2] = 0.8,
			[3] = 1,
		},
	},
	["QUESTTRACKER"] = false,
	["THREATMETERPLAYERONTOP"] = false,
	["AUTOREPAIRALL"] = false,
	["BloodBarsDelay"] = 0.2,
}
